name: Block ads update

on:
  schedule:
    - cron: '0 * * * *'
  push:
    branches:
      - '**'

jobs:
  block_ads_update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install jq, curl and other utilities
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl coreutils

      - name: Make script executable
        run: |
          chmod +x block_ads.sh

      - name: Run the script
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./block_ads.sh
